
  CREATE TABLE COMM_CODE 
   (	COMM_CD VARCHAR2(4) PRIMARY KEY , 
    	COMM_NM VARCHAR2(100) , 
        COMM_PARENT VARCHAR2(4) 
   ) ;

   COMMENT ON COLUMN COMM_CODE.COMM_CD IS '코드';
   COMMENT ON COLUMN COMM_CODE.COMM_NM IS '코드명';
   COMMENT ON COLUMN COMM_CODE.COMM_PARENT IS '부모 코드';
   COMMENT ON TABLE COMM_CODE  IS '공통코드 테이블';
   

Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB00','직업',null);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB01','주부','JB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB02','은행원','JB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB03','공무원','JB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB04','축산업','JB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB05','회사원','JB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB06','농업','JB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB07','자영업','JB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB08','학생','JB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('JB09','교사','JB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB00','취미',null);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB01','서예','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB02','장기','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB03','수영','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB04','독서','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB05','당구','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB06','바둑','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB07','볼링','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB08','스키','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB09','만화','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB10','낚시','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB11','영화감상','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB12','등산','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB13','개그','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB14','카레이싱','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('HB15','서핑','HB00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('BC00','글분류',null);
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('BC01','프로그램','BC00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('BC02','웹','BC00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('BC03','사는 이야기','BC00');
Insert into COMM_CODE (COMM_CD,COMM_NM,COMM_PARENT,COMM_ORD) values ('BC04','취업','BC00');


SELECT RPAD(' ', 4) || 'private ' ||
   CASE
   WHEN A.DATA_TYPE = 'VARCHAR2' THEN 'String'
   WHEN A.DATA_TYPE = 'NUMBER' THEN 'int'
   WHEN A.DATA_TYPE = 'FLOAT' THEN 'Dubale'
   WHEN A.DATA_TYPE = 'CHAR' AND A.DATA_LENGTH > 1 THEN 'String'
   WHEN A.DATA_TYPE = 'DATE' THEN 'String'
   ELSE 'Object'
   END ||
   ' ' ||
   CONCAT
   (
    LOWER(SUBSTR(B.COLUMN_NAME, 1, 1)),
    SUBSTR(REGEXP_REPLACE(INITCAP(B.COLUMN_NAME), ' |_'), 2)
   ) || CHR(59) || CHR(13)  AS columns
   ,  '/*'|| B.COMMENTS ||'*/'  AS comments
FROM   ALL_TAB_COLUMNS A
     , ALL_COL_COMMENTS B
WHERE  A.TABLE_NAME = B.TABLE_NAME
AND    A.COLUMN_NAME = B.COLUMN_NAME
AND    A.OWNER = 'JDBC'
AND    B.OWNER = 'JDBC'
AND    A.TABLE_NAME = 'COMM_CODE'
ORDER BY A.COLUMN_ID;